server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

# Log to console for Docker
logging:
  appenders:
    - type: console
      threshold: INFO
      target: stdout
    - type: console
      threshold: ERROR
      target: stderr